config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#index'
  resources :words do
  collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
  validates :content, presence: true, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update,:destroy]
  
  def index
    @words = Word.all
  end
  
  def new
    if params[:back]
      @word = Word.new(word_params)
    else
      @word = Word.new
    end
  end
  
  def create
    @word = Word.new(word_params)
    if @word.save
      redirect_to words_path, notice: "新規投稿を行いました!"
    else
      render 'new'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @word.update(word_params)
      redirect_to words_path, notice: "投稿内容を編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @word.destroy
    redirect_to words_path, notice:"投稿を削除しました！"
  end
  
  def confirm
    @word = Word.new(word_params)
    render :new if @word.invalid?
  end
  
  private

  def word_params
    params.require(:word).permit(:content)
  end
  
  def set_word
    @word = Word.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/words_helper.rb
module WordsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_words_path
    elsif action_name == 'edit'
      word_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phase2</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <header>
      
      <ul>
        <li><%= link_to 'HOME', root_path %>
        <li><%= link_to 'Word一覧', words_path %>
        <li><%= link_to '新規投稿', new_word_path %>
      </ul>
    </header>
  
  <%= yield %>
    
    <footer>
      <p>運営会社Sato株式会社</p>
      <p>© 2015-2016 Copyright Sato Corp.</p>
    </footer>
    
  </body>
</html>

app/views/tops/index.html.erb
<!--<!DOCTYPE html>-->
<!--<html lang="ja">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Achieve</title>-->
<!--    <link rel="stylesheet" href="normalize.css">-->
<!--    <link rel="stylesheet" href="style.css">-->
<!--</head>-->
<body>
  <!--<header>-->
  <!--  <ul>-->
  <!--    <li><a href="#">Achieve</a></li>-->
  <!--    <li><a href="#">トップページ</a></li>-->
  <!--    <li><a href="#">お問い合わせ</a></li>-->
  <!--    <li><a href="#">ブログ</a></li>-->
  <!--  </ul>-->
  <!--</header>-->
  <section class="main-header">
    <%= image_tag "achieve.png" %>
  </section>
  <section class="about">
    <h1>About Achieve</h1>
    <p>
      Achieveは、エンジニアになりたい人が集まるアプリです。<br>
      Achieveにエンジニアを目指す理由をつぶやきましょう。
    </p>
    
  </section>
  <section class="function">
    <h1>Function</h1>
    <div class="function-images">
      <div class="function-image">
        <img src="key.png">
        <p>ログイン機能</p>
      </div>
      <div class="function-image">
        <img src="mails.png">
        <p>メール送信機能</p>
      </div>
      <div class="function-image">
        <img src="girls.png">
        <p>友達つながり機能</p>
      </div>
      <div class="function-image">
        <img src="comment.png">
        <p>コメント投稿機能</p>
      </div>
    </div>
  </section>
  <footer>
    <p>運営会社sato株式会社</p>
    <p>© 2015-2016 Copyright sato Corp.</p>
  </footer>
</body>
</html>

app/views/words/_form.html.erb
<%= form_with(model: @word, local: true, url: choose_new_or_edit) do |form| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= @word.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="word_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="submit">
    <%= form.submit %>
  </div>
<% end %>



<%= link_to "投稿一覧画面にもどる", words_path %>

app/views/words/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @word, url: words_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @word.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @word, url: new_word_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/words/edit.html.erb
<h2>内容を編集する</h2>

  <%= render 'form' %>

app/views/words/index.html.erb
 <section class="main-header">
    <%= image_tag "achieve.png" %>
  </section>
  
<h1>投稿一覧</h1>

<p><%= notice %></p>
<div class = "table">
<table>
  <tr>
    <th>内容</th>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= word.content %></td>
    
    <td><%= link_to '詳細を確認する', word_path(word.id) , class: "btn btn-info "%></td>
    <td><%= link_to '投稿を編集する', edit_word_path(word.id),class: "btn btn-info ", data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to '投稿を削除する', word_path(word.id),  method: :delete ,class: "btn btn-info ",data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>
<%= link_to '新規投稿を行う', new_word_path %>
</div>

app/views/words/new.html.erb
<div class = "new">
<h2>新規投稿を行う</h2>
</div>

  <%= render 'form' %>

app/views/words/show.html.erb
<h1>投稿詳細画面</h1>
<p>内容: <%= @word.content %></p>